# Generated by Django 5.2.17 on 2026-08-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the address was confirmed by following an emailed link.', null=True),
        ),
    ]
