# Generated by Django 5.2.17 on 2026-08-29 16:24

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers come first in navigation.')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['position', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=60)),
                ('name_ru', models.CharField(max_length=60)),
                ('hex', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a six-digit hex colour, for example #0a0a0a.')])),
                ('is_dark', models.BooleanField(default=False, help_text='Whether the swatch needs light text or a lighter border.')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('garment', models.CharField(choices=[('tee', 'Tee'), ('hoodie', 'Hoodie'), ('cap', 'Cap'), ('beanie', 'Beanie'), ('tote', 'Tote')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='The struck-through price. Leave empty when not on sale.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('new', 'New'), ('sale', 'Sale'), ('bestseller', 'Bestseller')], max_length=20), blank=True, default=list, size=None)),
                ('description_en', models.TextField()),
                ('description_ru', models.TextField()),
                ('details_en', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('details_ru', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('is_active', models.BooleanField(default=True, help_text='Unset to hide from the storefront without deleting order history.')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['position', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(max_length=20)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ['product', 'color__slug', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'position'], name='catalog_pro_is_acti_68373b_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'size'), name='unique_variant_per_product_color_size'),
        ),
    ]
